CREATE FUNCTION  KiemTraMonHocDaThi
	(@MAMH NCHAR(5))
	RETURNS NCHAR(5)
AS
BEGIN
DECLARE @RESULT NCHAR(5)
SET @RESULT = ''
IF EXISTS (SELECT * FROM SINHVIEN , 
						(SELECT DISTINCT GV.MALOP, GV.MAMH, GV.LAN, BD.MASV FROM 
							GIAOVIEN_DANGKY GV, (SELECT * FROM BANGDIEM WHERE MAMH = @MAMH) BD
						WHERE GV.MAMH=BD.MAMH AND GV.LAN=BD.LAN AND GV.NGAYTHI=BD.NGAYTHI ) GVIEN
							WHERE GVIEN.MALOP = SINHVIEN.MALOP AND SINHVIEN.MASV = GVIEN.MASV)
BEGIN
	SET @RESULT = 'X'
END

RETURN @RESULT 
END
