DECLARE @TRINHDO NCHAR(1)
SELECT TOP 10 * FROM dbo.BODE 
	WHERE (
		IF @TRINHDO = 'A'
			BEGIN
				SELECT TOP 7 PERCENT * FROM dbo.BODE WHERE TRINHDO = @TRINHDO
				SELECT TOP 3 PERCENT * FROM dbo.BODE WHERE TRINHDO = @TRINHDO
			END

		ELSE IF @TRINHDO = 'B'
			BEGIN
				
			END
		ELSE 
			BEGIN
			END
	) 
ORDER BY NEWID()